module github.com/kconde2/vote-app

go 1.13

require (
	github.com/gin-contrib/sse v0.1.0 // indirect
	github.com/gin-gonic/gin v1.4.0
	github.com/golang/protobuf v1.3.2 // indirect
	github.com/howeyc/fsnotify v0.9.0 // indirect
	github.com/json-iterator/go v1.1.7 // indirect
	github.com/mattn/go-colorable v0.1.2 // indirect
	github.com/mattn/go-isatty v0.0.9 // indirect
	github.com/pilu/config v0.0.0-20131214182432-3eb99e6c0b9a // indirect
	github.com/pilu/fresh v0.0.0-20190826141211-0fa698148017 // indirect
	github.com/ugorji/go v1.1.7 // indirect
	golang.org/x/sys v0.0.0-20190913121621-c3b328c6e5a7 // indirect
)

// Generated by doing
// `go mod init github.com/kconde2/vote-app`
// `go get -u github.com/gin-gonic/gin`
